export const LOGIN_REQUEST = "LOGIN_REQUEST";
// export const LOGOUT_REQUEST = "LOGOUT_REQUEST";   //**11** 18 juin */

export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const CHECK_TOKEN = "CHECK_TOKEN";

export const CHECK_LEVEL_TEST = "CHECK_LEVEL_TEST";
export const GET_LEVEL_TESTS = "GET_LEVEL_TESTS";
export const HANDLE_RESPONSE = "HANDLE_RESPONSE";

export const GET_LEVEL_TEST_USER_SUMMARIES = "GET_LEVEL_TEST_USER_SUMMARIES";
