export const GET_USER_REQUEST = 'GET_USER_REQUEST';

export const CHECK_LEVEL_TEST ='CHECK_LEVEL_TEST';
export const GET_LEVEL_TESTS = 'GET_LEVEL_TESTS';
export const HANDLE_RESPONSE = 'HANDLE_RESPONSE';