export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"; 
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";  

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";

export const CHECK_LEVEL_TEST = "CHECK_LEVEL_TEST";
export const GET_LEVEL_TESTS = "GET_LEVEL_TESTS";
export const HANDLE_RESPONSE = "HANDLE_RESPONSE";

export const GET_LEVEL_TEST_USER_SUMMARIES = "GET_LEVEL_TEST_USER_SUMMARIES";
